### ISSUE TITLE
🚨 development branch is needed

### ISSUE THREAD

**Issue by lcfd** [noi-techpark/webcomp-meteo-generic#1]
I need the development branch in order to create pull requests.
If you can create it on every repository of the current project, thank you.

@Piiit @bertolla

**Comment by Piiit** [comment]
@lcfd Done, hopefully I found every missing branch in every repo... please reopen and write back, if I skipped one

**Comment by bertolla** [comment]
@Piiit If the project manager forget to create development branches it's no problem to redirect the pull request to master since we still will create the dev branch based on master and pull requests can be edited by us and changed to pull against development
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by Piiit** [comment]
@bertolla I knew that, and changed those PR destination branches already sometimes in other projects... Just saw this issue and wanted to check all repos quickly.
